# Generated by Django 4.2.4 on 2023-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('info', models.TextField(blank=True, verbose_name='info')),
            ],
        ),
    ]
