# Generated by Django 4.2.4 on 2023-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
