# Generated by Django 4.2.4 on 2023-11-29 23:03

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploaded_video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
