# Generated by Django 4.2.4 on 2023-12-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0006_alter_video_uploaded_video_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='whatsapp')),
                ('mail', models.CharField(max_length=50, verbose_name='mail')),
            ],
        ),
    ]
