# Generated by Django 4.2.4 on 2023-12-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0007_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mail',
            field=models.TextField(max_length=50, verbose_name='mail'),
        ),
    ]
