# Generated by Django 4.2.4 on 2023-12-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0009_remove_contactinfo_mail_remove_contactinfo_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info',
            field=models.TextField(max_length=50, null=True, verbose_name='contact_info'),
        ),
    ]
