# Generated by Django 4.2.4 on 2023-12-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynew', '0010_remove_contactinfo_whatsapp_contactinfo_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
